# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 294acb6ee9bb61ee68dd5ec2fef03e0eeacf7fade5a7f150e4c2996cc8945f2cc78b7ec15fb447f442127f63bac24fb608df216b26ead4d74d49f78f5bb17161

test:
  secret_key_base: 36e08ad2cbdfa02af20724335ce138279c3fda7f932c41ae374f88d6a03137d839342bcd80619f3f1a72254743a3a7c762c5a333e5b984c1d9903339e1aac3e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
